export * from './main'
export * from './about'
export * from './feature'
export * from './works'
export * from './pricing'
export * from './testimonials'
export * from './FAQ'
export * from './fotter'